# Generated by Django 5.2.3 on 2025-09-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0004_alter_professor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='professor',
            table='testimonials_professor',
        ),
    ]
