# Generated by Django 5.2.3 on 2025-09-05 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
    ]
